-- AlterTable
ALTER TABLE "SimulationState" ADD COLUMN     "averageSalary" DECIMAL(10,2) NOT NULL DEFAULT 3000,
ADD COLUMN     "basePrice" DECIMAL(10,2) NOT NULL DEFAULT 100,
ADD COLUMN     "customerSatisfaction" DOUBLE PRECISION NOT NULL DEFAULT 70,
ADD COLUMN     "loanPayments" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "marketSize" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "morale" DOUBLE PRECISION NOT NULL DEFAULT 70,
ADD COLUMN     "price" DECIMAL(10,2) NOT NULL DEFAULT 100;
