#!/usr/bin/env node

/**
 * Grok Consultation Script
 * Consults with Grok AI about DocumentIulia.ro technical issues
 */

import { generateText } from 'ai';
import { createXai } from '@ai-sdk/xai';
import * as fs from 'fs';
import * as path from 'path';

// Initialize Grok/XAI
const xai = createXai({
  apiKey: process.env.XAI_API_KEY || process.env.GROK_API_KEY || 'demo-key',
});

interface ConsultationContext {
  issue: string;
  currentState: {
    fixedItems: string[];
    workingAPIs: string[];
    failingAPIs: string[];
    frontendError: string;
  };
  questions: string[];
}

async function consultGrok(context: ConsultationContext): Promise<void> {
  console.log('\n🤖 Consulting with Grok AI...\n');
  console.log('━'.repeat(80));

  const systemPrompt = `You are Grok, an expert AI system architect and debugging assistant for DocumentIulia.ro,
a Romanian ERP/accounting platform built with Next.js 15, NestJS, PostgreSQL, and deployed on Hetzner with
Nginx reverse proxy and Cloudflare CDN.

Your expertise includes:
- Next.js App Router (v15) with client/server components
- NestJS authentication and authorization (JWT, guards)
- Frontend error boundaries and error handling
- API integration patterns and debugging
- Common causes of "Something went wrong" errors in production
- Romanian compliance (ANAF, e-Factura, VAT)

Provide detailed, actionable technical analysis focusing on root causes and solutions.`;

  const userPrompt = `
## Current Issue

${context.issue}

## What We've Fixed

${context.currentState.fixedItems.map(item => `✅ ${item}`).join('\n')}

## Current API Status

**Working APIs:**
${context.currentState.workingAPIs.map(api => `✅ ${api}`).join('\n')}

**Failing APIs:**
${context.currentState.failingAPIs.map(api => `❌ ${api}`).join('\n')}

**Frontend Error:**
"${context.currentState.frontendError}"

## Questions for Grok

${context.questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

Please provide:
1. Root cause analysis for the "Something went wrong" error
2. Specific code areas to investigate (file paths, functions)
3. Common Next.js 15 App Router issues that could cause this
4. Recommended debugging steps in order of priority
5. Any other endpoints that should be checked for dashboard functionality
`;

  try {
    const { text } = await generateText({
      model: xai('grok-2-1212'),
      system: systemPrompt,
      prompt: userPrompt,
      temperature: 0.3,
      maxTokens: 4000,
    });

    console.log('\n📋 Grok\'s Analysis:\n');
    console.log('━'.repeat(80));
    console.log(text);
    console.log('━'.repeat(80));

    // Save to file
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const outputPath = path.join(process.cwd(), 'logs', `grok-consultation-${timestamp}.md`);

    // Ensure logs directory exists
    const logsDir = path.join(process.cwd(), 'logs');
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }

    const fullReport = `# Grok Consultation Report
**Date:** ${new Date().toISOString()}
**Issue:** ${context.issue}

## Context

### Fixed Items
${context.currentState.fixedItems.map(item => `- ${item}`).join('\n')}

### Working APIs
${context.currentState.workingAPIs.map(api => `- ${api}`).join('\n')}

### Failing APIs
${context.currentState.failingAPIs.map(api => `- ${api}`).join('\n')}

### Frontend Error
\`\`\`
${context.currentState.frontendError}
\`\`\`

## Questions
${context.questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

## Grok's Analysis

${text}

---
*Generated by DocumentIulia.ro Grok Consultation Script*
`;

    fs.writeFileSync(outputPath, fullReport);
    console.log(`\n✅ Full report saved to: ${outputPath}\n`);

  } catch (error) {
    console.error('❌ Error consulting Grok:', error);

    if (error instanceof Error) {
      console.error('Error details:', error.message);

      // Provide fallback analysis if API fails
      console.log('\n⚠️  Grok API unavailable. Providing fallback analysis...\n');
      provideFallbackAnalysis(context);
    }
  }
}

function provideFallbackAnalysis(context: ConsultationContext): void {
  console.log('━'.repeat(80));
  console.log('📋 Fallback Analysis:\n');

  console.log('## Most Common Causes for "Something went wrong" with working APIs:\n');
  console.log('1. **Client-side Error Boundary Issue**');
  console.log('   - Check: /root/documentiulia.ro/src/app/error.tsx');
  console.log('   - Check: /root/documentiulia.ro/src/app/dashboard/error.tsx');
  console.log('   - Issue: Error boundary catching unrelated errors\n');

  console.log('2. **Token Storage/Retrieval Problem**');
  console.log('   - Check: localStorage/sessionStorage in browser DevTools');
  console.log('   - Check: Cookie settings and SameSite attributes');
  console.log('   - Issue: Token stored but not retrieved correctly\n');

  console.log('3. **Hydration Mismatch**');
  console.log('   - Check: Server/client rendering differences');
  console.log('   - Issue: useEffect or client-only code running during SSR\n');

  console.log('4. **Missing Environment Variables**');
  console.log('   - Check: NEXT_PUBLIC_* vars in browser Network tab');
  console.log('   - Issue: API URL or other vars undefined in client\n');

  console.log('5. **CORS or Preflight Issues**');
  console.log('   - Check: Browser Network tab for OPTIONS requests');
  console.log('   - Issue: Nginx not handling CORS properly for all methods\n');

  console.log('## Recommended Debugging Steps:\n');
  console.log('1. Check browser console for actual error (not generic message)');
  console.log('2. Add console.logs to dashboard page before API calls');
  console.log('3. Verify token in localStorage: localStorage.getItem("token")');
  console.log('4. Test dashboard API directly with curl using token');
  console.log('5. Check Nginx error logs: tail -f /var/log/nginx/error.log');
  console.log('6. Review Next.js build logs for hydration warnings\n');

  console.log('## Other Dashboard Endpoints to Check:\n');
  console.log('- GET /api/v1/users/me (current user profile)');
  console.log('- GET /api/v1/invoices (user invoices)');
  console.log('- GET /api/v1/compliance/vat (VAT data)');
  console.log('- GET /api/v1/analytics/insights (if using analytics)');
  console.log('- GET /api/v1/notifications (user notifications)');

  console.log('━'.repeat(80));
}

// Main execution
const consultationContext: ConsultationContext = {
  issue: 'User getting "Something went wrong - We\'re sorry, an unexpected error occurred" on frontend after successful login, despite APIs working correctly',
  currentState: {
    fixedItems: [
      'Fixed NEXT_PUBLIC_API_URL from /api to /api/v1',
      'Fixed Nginx missing Authorization header passthrough',
      'Verified login API works and returns token',
      'Verified dashboard stats API works with token',
    ],
    workingAPIs: [
      'POST /api/v1/auth/login (returns token)',
      'GET /api/v1/dashboard/stats (returns data with valid token)',
    ],
    failingAPIs: [
      'GET /api/v1/compliance/d112 (returns 500 error)',
    ],
    frontendError: 'Something went wrong - We\'re sorry, an unexpected error occurred',
  },
  questions: [
    'What could cause the "Something went wrong" error after login when APIs are working?',
    'Are there any known issues with Next.js error boundaries and client-side auth?',
    'What other endpoints should be checked for dashboard functionality?',
    'Could the failing D112 endpoint be causing a cascade failure on the dashboard?',
    'What are the most common causes of generic error messages in Next.js 15 App Router?',
  ],
};

consultGrok(consultationContext).catch(console.error);
