#!/usr/bin/env npx tsx
/**
 * Grok Sprint 25 Next Steps Consultation
 */

import { generateText } from 'ai';
import { createXai } from '@ai-sdk/xai';
import * as fs from 'fs';

const xai = createXai({
  apiKey: process.env.XAI_API_KEY || '',
});

async function consultGrok() {
  console.log('\n🤖 Consulting Grok for Sprint 25 Next Steps...\n');
  console.log('━'.repeat(80));

  const systemPrompt = `You are Grok, a strategic AI advisor for DocumentIulia.ro - a Romanian AI-powered ERP/accounting platform.
You understand business, technology, Romanian compliance (ANAF, e-Factura, SAF-T D406), and platform development.
Provide actionable, prioritized recommendations. Be concise but thorough. Focus on high-impact items.`;

  const userPrompt = `
## Sprint 25 Progress Report - December 25, 2025

### Completed Today:
1. ✅ Created 4 elite business services pages:
   - /services/business-formation (main overview)
   - /services/infiintare-srl (SRL formation with packages €199-499)
   - /services/inregistrare-pfa (PFA registration)
   - /services/forme-juridice (SA, SNC, SCS, ONG, Fundatie, II)

2. ✅ Seeded 10 SEO-optimized blog articles on business formation

3. ✅ Added 14 courses with full content (1,808 lessons total)

4. ✅ Added "Servicii" to main navigation

### Database Totals:
- 67 LMS courses with 435 modules, 1,808 lessons
- 38 published blog articles across 21 categories
- All content in Romanian with proper diacritics

### Sprint 25 Remaining Tasks:
1. [ ] Add 5 LMS courses on starting a business
2. [ ] Create templates library (contracts, invoices, declarations)
3. [ ] Forum content creation
4. [ ] Video tutorials (optional)

### Platform Current State:
- Frontend: Next.js 15 App Router, Tailwind, shadcn
- Backend: NestJS, PostgreSQL, Prisma
- 200+ dashboard button handlers wired
- Full Romanian compliance (ANAF, e-Factura, SAF-T D406)

## Questions for Grok:

1. What should be the next priority action for maximum business impact?
2. Should we focus on the 5 remaining LMS courses or the templates library first?
3. What types of templates would be most valuable for Romanian SMBs?
4. Any recommendations for improving the business services pages for conversion?
5. What SEO optimizations should we prioritize?
6. Rate our Sprint 25 progress (1-10) and explain.

Please provide a structured response with:
- Priority ranking of remaining tasks
- Specific recommendations for each
- Quick wins we can implement today
- Rating and feedback on current progress
`;

  try {
    const { text } = await generateText({
      model: xai('grok-2-1212'),
      system: systemPrompt,
      prompt: userPrompt,
      temperature: 0.4,
      maxTokens: 3000,
    });

    console.log('\n📋 Grok\'s Strategic Analysis:\n');
    console.log('━'.repeat(80));
    console.log(text);
    console.log('━'.repeat(80));

    // Save report
    const timestamp = new Date().toISOString().slice(0,19).replace(/[:.]/g, '');
    const report = `# Grok Sprint 25 Consultation
**Date:** ${new Date().toISOString()}

## Grok's Analysis

${text}

---
*Generated by DocumentIulia.ro Grok Consultation*
`;
    fs.writeFileSync(`GROK_REVIEW_${timestamp}.md`, report);
    console.log(`\n✅ Report saved to: GROK_REVIEW_${timestamp}.md\n`);

  } catch (error: any) {
    console.error('❌ Error:', error.message);
  }
}

consultGrok();
