/**
 * Romanian Test Companies Seed Data
 * 10 realistic Romanian companies for testing DocumentIulia.ro
 */

export const romanianTestCompanies = [
  {
    name: 'SC Digital Solutions SRL',
    cui: 'RO35789012',
    regCom: 'J40/1234/2020',
    address: 'Bulevardul Unirii nr. 45, et. 3',
    city: 'București',
    county: 'București',
    postalCode: '030167',
    email: 'contact@digitalsolutions.ro',
    phone: '+40213456789',
    website: 'https://digitalsolutions.ro',
    bankName: 'Banca Transilvania',
    iban: 'RO49BTRLRONCRT0123456789',
    swift: 'BTRLRO22',
    vatPayer: true,
    vatNumber: 'RO35789012',
    industry: 'IT & Software',
    employees: 25,
  },
  {
    name: 'Construct Expert SRL',
    cui: 'RO28456789',
    regCom: 'J12/567/2018',
    address: 'Strada Republicii nr. 78',
    city: 'Cluj-Napoca',
    county: 'Cluj',
    postalCode: '400015',
    email: 'office@constructexpert.ro',
    phone: '+40264789012',
    website: 'https://constructexpert.ro',
    bankName: 'BCR',
    iban: 'RO42RNCBROBU0000000001',
    swift: 'RNCBROBU',
    vatPayer: true,
    vatNumber: 'RO28456789',
    industry: 'Construcții',
    employees: 50,
  },
  {
    name: 'Agro Terra SRL',
    cui: 'RO15678901',
    regCom: 'J35/890/2015',
    address: 'Drumul Național 1, km 15',
    city: 'Timișoara',
    county: 'Timiș',
    postalCode: '300001',
    email: 'contact@agroterra.ro',
    phone: '+40256123456',
    website: 'https://agroterra.ro',
    bankName: 'Raiffeisen Bank',
    iban: 'RO35RZBR0000060000000001',
    swift: 'RZBRROBU',
    vatPayer: true,
    vatNumber: 'RO15678901',
    industry: 'Agricultură',
    employees: 120,
  },
  {
    name: 'Transport Rapid SRL',
    cui: 'RO42567890',
    regCom: 'J29/234/2021',
    address: 'Șoseaua București-Ploiești nr. 44',
    city: 'Ploiești',
    county: 'Prahova',
    postalCode: '100066',
    email: 'office@transportrapid.ro',
    phone: '+40244567890',
    website: 'https://transportrapid.ro',
    bankName: 'ING Bank',
    iban: 'RO49INGB0000999900000001',
    swift: 'INGBROBU',
    vatPayer: true,
    vatNumber: 'RO42567890',
    industry: 'Transport & Logistică',
    employees: 35,
  },
  {
    name: 'Retail Plus SRL',
    cui: 'RO19876543',
    regCom: 'J40/5678/2019',
    address: 'Calea Victoriei nr. 120',
    city: 'București',
    county: 'București',
    postalCode: '010093',
    email: 'contact@retailplus.ro',
    phone: '+40214567890',
    website: 'https://retailplus.ro',
    bankName: 'BRD',
    iban: 'RO12BRDE450SV00000000001',
    swift: 'BRDEROBU',
    vatPayer: true,
    vatNumber: 'RO19876543',
    industry: 'Retail',
    employees: 80,
  },
  {
    name: 'MedCare Clinic SRL',
    cui: 'RO33445566',
    regCom: 'J16/789/2017',
    address: 'Strada Cuza Vodă nr. 15',
    city: 'Iași',
    county: 'Iași',
    postalCode: '700036',
    email: 'contact@medcareclinic.ro',
    phone: '+40232456789',
    website: 'https://medcareclinic.ro',
    bankName: 'UniCredit',
    iban: 'RO69BACX0000000012345678',
    swift: 'BACXROBU',
    vatPayer: false, // Medical services exempt
    vatNumber: null,
    industry: 'Sănătate',
    employees: 45,
  },
  {
    name: 'Hotel Majestic SA',
    cui: 'RO11223344',
    regCom: 'J09/123/2010',
    address: 'Bulevardul Mamaia nr. 250',
    city: 'Constanța',
    county: 'Constanța',
    postalCode: '900001',
    email: 'rezervari@hotelmajestic.ro',
    phone: '+40241234567',
    website: 'https://hotelmajestic.ro',
    bankName: 'Alpha Bank',
    iban: 'RO86BUCU0000000000000001',
    swift: 'BUCUROBU',
    vatPayer: true,
    vatNumber: 'RO11223344',
    industry: 'Turism & Hospitality',
    employees: 150,
  },
  {
    name: 'EcoEnergy Solutions SRL',
    cui: 'RO44556677',
    regCom: 'J23/456/2022',
    address: 'Parcul Industrial Vest, Hala 5',
    city: 'Sibiu',
    county: 'Sibiu',
    postalCode: '550024',
    email: 'office@ecoenergy.ro',
    phone: '+40269345678',
    website: 'https://ecoenergy.ro',
    bankName: 'CEC Bank',
    iban: 'RO73CECEB00000RON0000001',
    swift: 'CECEROBU',
    vatPayer: true,
    vatNumber: 'RO44556677',
    industry: 'Energie & Utilities',
    employees: 28,
  },
  {
    name: 'Food Factory SRL',
    cui: 'RO55667788',
    regCom: 'J05/890/2016',
    address: 'Zona Industrială, str. Fabricii nr. 10',
    city: 'Brașov',
    county: 'Brașov',
    postalCode: '500460',
    email: 'comenzi@foodfactory.ro',
    phone: '+40268567890',
    website: 'https://foodfactory.ro',
    bankName: 'OTP Bank',
    iban: 'RO96OTPV0000000000000001',
    swift: 'OTPVROBU',
    vatPayer: true,
    vatNumber: 'RO55667788',
    industry: 'Producție Alimentară',
    employees: 200,
  },
  {
    name: 'Media Vision SRL',
    cui: 'RO66778899',
    regCom: 'J40/7890/2023',
    address: 'Strada Știrbei Vodă nr. 88',
    city: 'București',
    county: 'București',
    postalCode: '010105',
    email: 'hello@mediavision.ro',
    phone: '+40215678901',
    website: 'https://mediavision.ro',
    bankName: 'First Bank',
    iban: 'RO45FIRB0000000000000001',
    swift: 'FIRBROBU',
    vatPayer: true,
    vatNumber: 'RO66778899',
    industry: 'Marketing & Publicitate',
    employees: 15,
  },
];

// Test clients for each company
export const testClients = [
  { name: 'Partener Business SRL', cui: 'RO12121212', type: 'BUSINESS', city: 'București' },
  { name: 'SC Furnizor Pro SRL', cui: 'RO23232323', type: 'BUSINESS', city: 'Cluj-Napoca' },
  { name: 'Distribuitor National SA', cui: 'RO34343434', type: 'BUSINESS', city: 'Timișoara' },
  { name: 'Client Premium SRL', cui: 'RO45454545', type: 'BUSINESS', city: 'Iași' },
  { name: 'Ion Popescu PFA', cui: 'RO56565656', type: 'INDIVIDUAL', city: 'București' },
  { name: 'Maria Ionescu PFA', cui: 'RO67676767', type: 'INDIVIDUAL', city: 'Constanța' },
  { name: 'Ministerul Educației', cui: 'RO78787878', type: 'GOVERNMENT', city: 'București' },
  { name: 'Primăria Sector 1', cui: 'RO89898989', type: 'GOVERNMENT', city: 'București' },
];

// Test products/services
export const testProducts = [
  { name: 'Consultanță IT', type: 'SERVICE', price: 500, unit: 'ora', vatRate: 19 },
  { name: 'Dezvoltare Web', type: 'SERVICE', price: 2500, unit: 'proiect', vatRate: 19 },
  { name: 'Laptop Business', type: 'PRODUCT', price: 4500, unit: 'buc', vatRate: 19 },
  { name: 'Licență Software', type: 'SERVICE', price: 1200, unit: 'an', vatRate: 19 },
  { name: 'Servicii Contabilitate', type: 'SERVICE', price: 800, unit: 'lună', vatRate: 19 },
  { name: 'Materiale Construcții', type: 'PRODUCT', price: 15000, unit: 'tonă', vatRate: 19 },
  { name: 'Transport Marfă', type: 'SERVICE', price: 350, unit: 'cursă', vatRate: 19 },
  { name: 'Cazare Hotel', type: 'SERVICE', price: 450, unit: 'noapte', vatRate: 9 },
  { name: 'Masă Restaurant', type: 'SERVICE', price: 75, unit: 'persoană', vatRate: 9 },
  { name: 'Produse Alimentare', type: 'PRODUCT', price: 25, unit: 'kg', vatRate: 9 },
];

// Romanian counties for random selection
export const romanianCounties = [
  'Alba', 'Arad', 'Argeș', 'Bacău', 'Bihor', 'Bistrița-Năsăud', 'Botoșani', 'Brașov',
  'Brăila', 'București', 'Buzău', 'Caraș-Severin', 'Călărași', 'Cluj', 'Constanța',
  'Covasna', 'Dâmbovița', 'Dolj', 'Galați', 'Giurgiu', 'Gorj', 'Harghita', 'Hunedoara',
  'Ialomița', 'Iași', 'Ilfov', 'Maramureș', 'Mehedinți', 'Mureș', 'Neamț', 'Olt',
  'Prahova', 'Satu Mare', 'Sălaj', 'Sibiu', 'Suceava', 'Teleorman', 'Timiș', 'Tulcea',
  'Vaslui', 'Vâlcea', 'Vrancea',
];

// Romanian bank list
export const romanianBanks = [
  { name: 'Banca Transilvania', swift: 'BTRLRO22', prefix: 'BTRL' },
  { name: 'BCR', swift: 'RNCBROBU', prefix: 'RNCB' },
  { name: 'BRD', swift: 'BRDEROBU', prefix: 'BRDE' },
  { name: 'ING Bank', swift: 'INGBROBU', prefix: 'INGB' },
  { name: 'Raiffeisen Bank', swift: 'RZBRROBU', prefix: 'RZBR' },
  { name: 'UniCredit', swift: 'BACXROBU', prefix: 'BACX' },
  { name: 'Alpha Bank', swift: 'BUCUROBU', prefix: 'BUCU' },
  { name: 'CEC Bank', swift: 'CECEROBU', prefix: 'CECE' },
  { name: 'OTP Bank', swift: 'OTPVROBU', prefix: 'OTPV' },
  { name: 'First Bank', swift: 'FIRBROBU', prefix: 'FIRB' },
];
