/**
 * BC-107 — assemble a Business-Case deliverable (HTML) from a template skeleton,
 * the assumption set, and the BC-104/105 appraisal, at a chosen HM-Treasury
 * maturity (SOC → OBC → FBC). Pure & synchronous: charts are passed in as data
 * URIs so this is unit-testable for section inclusion without a canvas.
 */
import Handlebars from 'handlebars';
import { AppraisalResult } from './bc.model';
import { TornadoBar, MonteCarloResult } from './bc.sensitivity';

export type Maturity = 'SOC' | 'OBC' | 'FBC';

/** Which FIVE_CASE skeleton sections each maturity renders. */
const MATURITY_SECTIONS: Record<Maturity, string[]> = {
  SOC: ['Strategic', 'Economic'],
  OBC: ['Strategic', 'Economic', 'Commercial', 'Financial', 'Management'],
  FBC: ['Strategic', 'Economic', 'Commercial', 'Financial', 'Management'],
};
const SENSITIVITY_ANNEX: Record<Maturity, boolean> = { SOC: false, OBC: false, FBC: true };

export interface DeliverableInput {
  title: string;
  template: string;
  skeleton: string[];
  maturity: Maturity;
  locale: 'ro' | 'en';
  answers: Record<string, any>;
  appraisal: AppraisalResult;
  tornado: TornadoBar[];
  monteCarlo: MonteCarloResult;
  /** data: URIs from ChartService (optional; omitted in unit tests). */
  charts?: { npvByYear?: string; tornado?: string; mcHistogram?: string };
}

/** Sections to render = skeleton ∩ maturity allow-list (falls back to full skeleton). */
export function sectionsForMaturity(skeleton: string[], maturity: Maturity): string[] {
  const allow = MATURITY_SECTIONS[maturity];
  const filtered = skeleton.filter((s) => allow.includes(s));
  return filtered.length ? filtered : skeleton;
}

const L = {
  ro: { maturity: 'Maturitate', rate: 'Rata de actualizare', npv: 'VAN', irr: 'RIR', payback: 'Recuperare',
    dpayback: 'Recuperare actualizată', bcr: 'Raport beneficiu-cost', roi: 'RI', years: 'ani', noRoot: 'fără soluție',
    annex: 'Anexă — analiză de senzitivitate', mc: 'Monte-Carlo (distribuția VAN)', tornado: 'Tornado (±10%)',
    prob: 'Prob. VAN > 0', probIrr: 'Prob. RIR > prag', generated: 'Generat de DocumentIulia' },
  en: { maturity: 'Maturity', rate: 'Discount rate', npv: 'NPV', irr: 'IRR', payback: 'Payback',
    dpayback: 'Discounted payback', bcr: 'Benefit-cost ratio', roi: 'ROI', years: 'yrs', noRoot: 'no root',
    annex: 'Annex — sensitivity analysis', mc: 'Monte-Carlo (NPV distribution)', tornado: 'Tornado (±10%)',
    prob: 'Prob. NPV > 0', probIrr: 'Prob. IRR > hurdle', generated: 'Generated by DocumentIulia' },
};

const SECTION_BLURB: Record<string, { ro: string; en: string }> = {
  Strategic: { ro: 'Motivația schimbării, obiectivele și alinierea strategică.', en: 'The case for change, objectives and strategic fit.' },
  Economic: { ro: 'Opțiunile evaluate și VAN/RIR pentru opțiunea preferată.', en: 'Options appraised and NPV/IRR for the preferred option.' },
  Commercial: { ro: 'Aranjamentele comerciale, achiziția și alocarea riscului.', en: 'Commercial arrangements, procurement and risk allocation.' },
  Financial: { ro: 'Accesibilitatea și impactul bugetar pe orizontul de analiză.', en: 'Affordability and budget impact across the horizon.' },
  Management: { ro: 'Guvernanța, planul de livrare și managementul beneficiilor.', en: 'Governance, delivery plan and benefits management.' },
};

const escape = Handlebars.escapeExpression;
const money = (n: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(n);

/** Build the deliverable HTML for the given maturity. */
export function buildDeliverableHtml(input: DeliverableInput): string {
  const t = L[input.locale] ?? L.en;
  const sections = sectionsForMaturity(input.skeleton, input.maturity);
  const a = input.appraisal;
  const irrStr = a.irr === null ? t.noRoot : `${(a.irr * 100).toFixed(2)}%`;

  const sectionHtml = sections.map((s) => {
    const blurb = SECTION_BLURB[s] ? (input.locale === 'ro' ? SECTION_BLURB[s].ro : SECTION_BLURB[s].en) : '';
    let extra = '';
    if (s === 'Economic') {
      extra = `
        <table class="metrics">
          <tr><th>${t.npv}</th><td>${money(a.npv)}</td><th>${t.irr}</th><td>${irrStr}</td></tr>
          <tr><th>${t.payback}</th><td>${a.paybackYears ?? '—'} ${t.years}</td><th>${t.dpayback}</th><td>${a.discountedPaybackYears ?? '—'} ${t.years}</td></tr>
          <tr><th>${t.bcr}</th><td>${a.bcr}</td><th>${t.roi}</th><td>${(a.roi * 100).toFixed(1)}%</td></tr>
        </table>
        ${input.charts?.npvByYear ? `<img class="chart" src="${input.charts.npvByYear}" alt="NPV by year" />` : ''}`;
    }
    return `<section><h2>${escape(s)}</h2><p>${escape(blurb)}</p>${extra}</section>`;
  }).join('\n');

  const annexHtml = SENSITIVITY_ANNEX[input.maturity] ? `
    <section class="annex"><h2>${t.annex}</h2>
      <p>${t.prob}: <b>${(input.monteCarlo.probNpvPositive * 100).toFixed(0)}%</b> ·
         ${t.probIrr}: <b>${(input.monteCarlo.probIrrAboveHurdle * 100).toFixed(0)}%</b> ·
         P10 ${money(input.monteCarlo.p10)} · P50 ${money(input.monteCarlo.p50)} · P90 ${money(input.monteCarlo.p90)}</p>
      ${input.charts?.tornado ? `<img class="chart" src="${input.charts.tornado}" alt="Tornado" />` : ''}
      ${input.charts?.mcHistogram ? `<img class="chart" src="${input.charts.mcHistogram}" alt="Monte-Carlo" />` : ''}
      <table class="metrics"><tr><th>${t.tornado}</th><th>low</th><th>high</th><th>swing</th></tr>
        ${input.tornado.map((b) => `<tr><td>${escape(b.key)}</td><td>${money(b.lowNpv)}</td><td>${money(b.highNpv)}</td><td>${money(b.swing)}</td></tr>`).join('')}
      </table>
    </section>` : '';

  const tpl = Handlebars.compile(`<!doctype html><html lang="{{locale}}"><head><meta charset="utf-8" />
    <style>
      body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; margin: 32px; }
      h1 { font-size: 22px; margin-bottom: 2px; }
      .meta { color: #555; font-size: 12px; margin-bottom: 16px; }
      .badge { display:inline-block; background:#0b7681; color:#fff; border-radius:4px; padding:2px 8px; font-size:11px; }
      section { margin: 14px 0; page-break-inside: avoid; }
      h2 { font-size: 15px; border-bottom: 1px solid #ddd; padding-bottom: 3px; }
      table.metrics { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 12px; }
      table.metrics th, table.metrics td { border: 1px solid #ddd; padding: 4px 8px; text-align: left; }
      table.metrics th { background: #f3f4f6; }
      img.chart { max-width: 100%; margin: 8px 0; border: 1px solid #eee; }
      .annex { border-top: 2px solid #0b7681; }
      footer { margin-top: 24px; color:#888; font-size: 10px; }
    </style></head><body>
    <h1>{{title}}</h1>
    <div class="meta"><span class="badge">{{maturityLabel}}: {{maturity}}</span> · {{template}} · {{rateLabel}} {{rateStr}}</div>
    {{{sections}}}
    {{{annex}}}
    <footer>{{generated}} · {{now}}</footer>
    </body></html>`);

  return tpl({
    locale: input.locale,
    title: input.title,
    maturity: input.maturity,
    maturityLabel: t.maturity,
    template: input.template,
    rateLabel: t.rate,
    rateStr: `${(a.discountRate * 100).toFixed(2)}% (${a.discountMethod.toUpperCase()})`,
    sections: sectionHtml,
    annex: annexHtml,
    generated: t.generated,
    now: input.answers['__now'] ?? '',
  });
}
