import { BcBranding } from './bc.charts';
import { Maturity } from './bc.deliverable';

/**
 * BC-304 — board deck (PptxGenJS). 10–15 slides, maturity-aware (SOC is the
 * shortest), RO/EN, charts as ChartService-rendered PNGs (base64) — no chart
 * code of its own (BC-301 contract).
 */

// eslint-disable-next-line @typescript-eslint/no-var-requires
const PptxGenJS = require('pptxgenjs');

export interface PptxDeckInput {
  title: string;
  template: string;
  maturity: Maturity;
  locale: 'ro' | 'en';
  results: any; // resultsJson shape (appraisal/extras/extended/tornado/monteCarlo/unitEconomics/rfq)
  chartsPng: { cashTrajectory?: string; tornado?: string; mcHistogram?: string; debtDscr?: string }; // base64 (no data: prefix)
  branding?: BcBranding | null;
}

const T = {
  ro: {
    execSummary: 'Rezumat executiv',
    metrics: 'Indicatori-cheie',
    cash: 'Fluxuri de numerar',
    sensitivity: 'Sensibilitate (tornado)',
    mc: 'Simulare Monte-Carlo',
    debt: 'Finanțare & DSCR',
    ue: 'Economia unitară',
    rfq: 'Ofertare (RFQ)',
    risks: 'Riscuri principale',
    assumptions: 'Ipoteze principale',
    recommendation: 'Recomandare',
    disclaimer: 'Notă',
    disclaimerText: 'Document generat automat de DocumentIulia. Nu constituie consultanță financiară sau juridică.',
    positive: 'VAN pozitiv — proiectul creează valoare la rata de actualizare aleasă.',
    negative: 'VAN negativ — proiectul nu se justifică la rata de actualizare aleasă.',
    dscrWarn: 'Atenție: DSCR sub 1.0 în cel puțin o perioadă — serviciul datoriei nu este acoperit.',
  },
  en: {
    execSummary: 'Executive summary',
    metrics: 'Key metrics',
    cash: 'Cash flows',
    sensitivity: 'Sensitivity (tornado)',
    mc: 'Monte-Carlo simulation',
    debt: 'Financing & DSCR',
    ue: 'Unit economics',
    rfq: 'RFQ costing',
    risks: 'Key risks',
    assumptions: 'Key assumptions',
    recommendation: 'Recommendation',
    disclaimer: 'Note',
    disclaimerText: 'Automatically generated by DocumentIulia. Not financial or legal advice.',
    positive: 'Positive NPV — the project creates value at the chosen discount rate.',
    negative: 'Negative NPV — the project is not justified at the chosen discount rate.',
    dscrWarn: 'Warning: DSCR below 1.0 in at least one period — debt service is not covered.',
  },
};

const fmt = (v: number | null | undefined, digits = 0): string =>
  v === null || v === undefined || Number.isNaN(Number(v)) ? 'n/a' : Number(v).toLocaleString('en-GB', { maximumFractionDigits: digits });
const pct = (v: number | null | undefined): string => (v === null || v === undefined ? 'n/a' : `${(Number(v) * 100).toFixed(1)}%`);

/** Build the deck; returns { buffer, slideCount }. */
export async function buildBoardDeck(input: PptxDeckInput): Promise<{ buffer: Buffer; slideCount: number }> {
  const t = T[input.locale];
  const primary = input.branding?.primaryColor?.replace('#', '') || '0B7681';
  const accent = input.branding?.accentColor?.replace('#', '') || 'C79A3A';
  const r = input.results ?? {};
  const ap = r.appraisal ?? {};
  const ex = r.extras ?? {};
  const ext = r.extended ?? null;

  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'A4L', width: 11.69, height: 8.27 });
  pptx.layout = 'A4L';
  let slideCount = 0;

  const addTitleBar = (slide: any, text: string) => {
    slide.addShape('rect', { x: 0, y: 0, w: 11.69, h: 0.7, fill: { color: primary } });
    slide.addText(text, { x: 0.4, y: 0.08, w: 10.8, h: 0.55, color: 'FFFFFF', fontSize: 20, bold: true });
    if (input.branding?.footerText) {
      slide.addText(input.branding.footerText, { x: 0.4, y: 7.85, w: 10.8, h: 0.35, fontSize: 9, color: '888888' });
    }
  };
  const newSlide = (title: string) => {
    const s = pptx.addSlide();
    addTitleBar(s, title);
    slideCount++;
    return s;
  };

  // 1 — Title
  const s1 = pptx.addSlide();
  slideCount++;
  s1.addShape('rect', { x: 0, y: 3.0, w: 11.69, h: 1.8, fill: { color: primary } });
  s1.addText(input.title, { x: 0.6, y: 3.15, w: 10.4, h: 1.0, color: 'FFFFFF', fontSize: 32, bold: true });
  s1.addText(`${input.template} · ${input.maturity}`, { x: 0.6, y: 4.1, w: 10.4, h: 0.5, color: 'FFFFFF', fontSize: 16 });
  if (input.branding?.logoDataUri) {
    s1.addImage({ data: input.branding.logoDataUri, x: 9.8, y: 0.4, w: 1.4, h: 1.4 });
  }

  // 2 — Exec summary
  const s2 = newSlide(t.execSummary);
  const verdict = (ap.npv ?? 0) >= 0 ? t.positive : t.negative;
  const bullets = [
    `NPV: ${fmt(ap.npv, 2)} · IRR: ${pct(ap.irr)} · MIRR: ${pct(ex.mirr)}`,
    verdict,
    ...(ext?.dscrWarning ? [t.dscrWarn] : []),
  ];
  s2.addText(bullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })), { x: 0.6, y: 1.2, w: 10.4, h: 3.5, fontSize: 16 });

  // 3 — Metrics tiles
  const s3 = newSlide(t.metrics);
  const tiles: [string, string][] = [
    ['NPV', fmt(ap.npv, 2)],
    ['IRR', pct(ap.irr)],
    ['MIRR', pct(ex.mirr)],
    ['Payback', ap.paybackYears != null ? `${Number(ap.paybackYears).toFixed(2)}y` : 'n/a'],
    ['Min DSCR', ext?.coverage?.minDscr != null ? Number(ext.coverage.minDscr).toFixed(2) : 'n/a'],
    ['EAC', fmt(ex.eac, 2)],
  ];
  tiles.forEach(([label, value], i) => {
    const x = 0.6 + (i % 3) * 3.6;
    const y = 1.4 + Math.floor(i / 3) * 2.2;
    const s = s3;
    s.addShape('roundRect', { x, y, w: 3.2, h: 1.8, fill: { color: 'F4F6F8' }, line: { color: primary } });
    s.addText(label, { x: x + 0.2, y: y + 0.15, w: 2.8, h: 0.4, fontSize: 13, color: '666666' });
    s.addText(value, { x: x + 0.2, y: y + 0.6, w: 2.8, h: 0.9, fontSize: 24, bold: true, color: primary });
  });

  // 4 — Cash-flow chart
  if (input.chartsPng.cashTrajectory) {
    const s = newSlide(t.cash);
    s.addImage({ data: `data:image/png;base64,${input.chartsPng.cashTrajectory}`, x: 1.2, y: 1.3, w: 9.2, h: 5.6 });
  }
  // 5 — Tornado
  if (input.chartsPng.tornado) {
    const s = newSlide(t.sensitivity);
    s.addImage({ data: `data:image/png;base64,${input.chartsPng.tornado}`, x: 1.2, y: 1.3, w: 9.2, h: 5.6 });
  }
  // 6 — Monte-Carlo
  if (input.chartsPng.mcHistogram) {
    const s = newSlide(t.mc);
    const mc = r.monteCarlo ?? {};
    s.addImage({ data: `data:image/png;base64,${input.chartsPng.mcHistogram}`, x: 1.2, y: 1.3, w: 7.4, h: 5.4 });
    s.addText(`P10 ${fmt(mc.p10, 0)}\nP50 ${fmt(mc.p50, 0)}\nP90 ${fmt(mc.p90, 0)}\nP(NPV>0) ${mc.probNpvPositive != null ? (mc.probNpvPositive * 100).toFixed(0) + '%' : 'n/a'}`, { x: 8.8, y: 1.6, w: 2.4, h: 3.2, fontSize: 14 });
  }

  // OBC/FBC depth slides
  if (input.maturity !== 'SOC') {
    if (input.chartsPng.debtDscr || ext?.debtSchedule) {
      const s = newSlide(t.debt);
      if (input.chartsPng.debtDscr) s.addImage({ data: `data:image/png;base64,${input.chartsPng.debtDscr}`, x: 1.2, y: 1.3, w: 9.2, h: 5.6 });
      else s.addText(t.dscrWarn, { x: 0.6, y: 1.4, w: 10.4, h: 1.2, fontSize: 14 });
    }
    if (r.unitEconomics) {
      const s = newSlide(t.ue);
      const ue = r.unitEconomics;
      s.addText(
        [`CAC ${fmt(ue.cac, 2)}`, `LTV ${fmt(ue.ltv, 2)}${ue.capped ? ' (capped)' : ''}`, `LTV/CAC ${fmt(ue.ltvToCac, 2)}`, `CAC payback ${fmt(ue.cacPaybackMonths, 1)} mo`].map((x) => ({ text: x, options: { bullet: true, breakLine: true } })),
        { x: 0.6, y: 1.3, w: 10.4, h: 3.4, fontSize: 18 },
      );
    }
  }
  if (input.maturity === 'FBC' && r.rfq) {
    const s = newSlide(t.rfq);
    s.addText(
      [`Full cost ${fmt(r.rfq.costSheet?.fullCost, 2)}`, `Price ${fmt(r.rfq.price, 2)}`, `Bid score ${fmt(r.rfq.bidScore, 0)} → ${r.rfq.recommendation ?? ''}`].map((x) => ({ text: x, options: { bullet: true, breakLine: true } })),
      { x: 0.6, y: 1.3, w: 10.4, h: 3.0, fontSize: 18 },
    );
  }

  // Risks
  const sr = newSlide(t.risks);
  const riskBullets: string[] = [];
  (Array.isArray(r.tornado) ? r.tornado.slice(0, 3) : []).forEach((b: any) => riskBullets.push(`${b.key}: ΔNPV ±${fmt(Math.abs(b.swing), 0)}`));
  if (ext?.dscrWarning) riskBullets.push(t.dscrWarn);
  const probNeg = r.monteCarlo?.probNpvPositive != null ? 1 - r.monteCarlo.probNpvPositive : null;
  if (probNeg != null) riskBullets.push(`P(NPV<0): ${(probNeg * 100).toFixed(0)}%`);
  if (!riskBullets.length) riskBullets.push('n/a');
  sr.addText(riskBullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })), { x: 0.6, y: 1.3, w: 10.4, h: 4.0, fontSize: 16 });

  // Assumptions recap (keeps SOC ≥ 10 slides)
  const sa = newSlide(t.assumptions);
  sa.addText(
    [`Discount ${pct(ap.discountRate)}`, `Horizon ${Math.max(...(ap.cashflows ?? [{ year: 0 }]).map((c: any) => c.year))}y`, `BCR ${fmt(ap.bcr, 2)}`, `ROI ${pct(ap.roi)}`].map((x) => ({ text: x, options: { bullet: true, breakLine: true } })),
    { x: 0.6, y: 1.3, w: 10.4, h: 3.0, fontSize: 16 },
  );

  // Recommendation
  const srec = newSlide(t.recommendation);
  srec.addShape('roundRect', { x: 0.6, y: 1.6, w: 10.4, h: 2.2, fill: { color: 'F4F6F8' }, line: { color: accent } });
  srec.addText(verdict, { x: 0.9, y: 2.0, w: 9.8, h: 1.4, fontSize: 20, bold: true, color: primary });

  // Disclaimer / closing
  const sd = newSlide(t.disclaimer);
  sd.addText(t.disclaimerText, { x: 0.6, y: 1.5, w: 10.4, h: 1.2, fontSize: 13, color: '666666' });

  const buffer: Buffer = await pptx.write('nodebuffer');
  return { buffer, slideCount };
}
